# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170509_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hight_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='hight_field', null=True, upload_to=b'', width_field='width_field'),
        ),
    ]
